# Site settings
title: Hubert Bryłkowski
description: Business card
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hubert Bryłkowski
user_title: Backend Engineer
email: hubert@brylkowski.com
twitter_username: hubbry
github_username:  hbrylkowski
linkedin_profile: hubert-brylkowski

# Google-analytics
google-analytics:
  id: "UA-144134670-1"

exclude: ['package.json', 'src' , 'node_modules']
